### PR TITLE
Add Flash component

### PR DESCRIPTION
**Pull request by mark-cipolla**
It's lifted from TC Analytics, and a good candidate for our shared library!

This PR also adds [Knobs](https://www.npmjs.com/package/@storybook/addon-knobs) support, so we can fiddle with components' props to our hearts content.

flassssssh

### CODE REVIEW

**Comment by mark-cipolla** [comment]
[Add Flash component](https://trello.com/c/pgCx6dC2/10905-add-flash-component)

**Comment by tiagoamaro** [comment]
This is incredible @markcipolla 🎉 

I've noticed that there's a small white space between the top of the page and the flash message: 

image

It seems somewhere margins are set to have `em`s measure, since this 12px is coming from the `font-size` property.

**Comment by mark-cipolla** [comment]
> I've noticed that there's a small white space between the top of the page and the flash message:

Fixed that.

Also fixed the styling slightly; TC had some extra background styles, plus I fixed a few small issues with placement (it wasn't _quite_ horizontally aligned).

I think it's good to go now!

**Review by nullobject — CHANGES_REQUESTED** [review]
You're missing the `package-lock.json` file.

**Comment by benmacleod** [comment]
I like it. Knobs is a good find, too 👍

**Comment by nullobject** [comment]
Is there any way we can avoid having to display the flash messages on separate pages? It would be awesome if we could have something like the bootstrap example where they render them all together: https://getbootstrap.com/docs/4.0/components/alerts/#examples

**Comment by mark-cipolla** [comment]
> Is there any way we can avoid having to display the flash messages on separate pages? It would be awesome if we could have something like the bootstrap example where they render them all together:

Not really, no. They are all `position: fixed`, so they sit over the top of each other.

**Comment by benmacleod** [comment]
> Is there any way we can avoid having to display the flash messages on separate pages? 

If you wanted to allow toggling between the different types, you could use Knobs perhaps? e.g. https://www.npmjs.com/package/@storybook/addon-knobs#select. 

If you take this sort of an approach, it could mean you wouldn't need a lot of different pages for many different components.

**Comment by nullobject** [comment]
> Not really, no. They are all position: fixed, so they sit over the top of each other.

Firstly, I don't like the inconsistency with the way we render all our storybook components (under the Display heading). Why should this one be different? To me that's a smell. Our design guide is already becoming inconsistent and we've only just started 😃 

My main concern is that it seems less reusable to have a shared component which has to be used in a certain way. Do all our apps display alerts in exactly the same way? I get that we are not trying to rebuild bootstrap here, but maybe we should aim to keep things generic and reusable?

@nickbrowne Do you have any opinions?

**Comment by mark-cipolla** [comment]
> If you wanted to allow toggling between the different types, you could use Knobs perhaps? e.g. https://www.npmjs.com/package/@storybook/addon-knobs#select

That's a good idea. Done.

flaaaash

**Comment by nickbrowne** [comment]
> Firstly, I don't like the inconsistency with the way we render all our storybook components (under the Display heading). Why should this one be different? To me that's a smell. Our design guide is already becoming inconsistent and we've only just started smiley
> 
> My main concern is that it seems less reusable to have a shared component which has to be used in a certain way. Do all our apps display alerts in exactly the same way? I get that we are not trying to rebuild bootstrap here, but maybe we should aim to keep things generic and reusable?
> 
> @nickbrowne Do you have any opinions?

I brought this same point up before most of this started, to me the custom headings are non-standard and unnecessary, as the sidebar already communicates well enough what is selected. Documenting the flash message also shows that we'll run into layout issues when combining particular components with the custom headings.

There are some other issues here as well, though they relate more to the (again, arguably non-standard) implementation of "Rails" flash messages themselves. It's a UX nightmare when you have multiple flash messages to show a user and they just end up overlapping.

Rails flash messages out of the box actually have more desirable traits than our custom flash messages. They don't disappear automatically, so people don't need to keep an eagle eye on the top of their screen, and if there are multiples notices, they just stack on top of each other.

Simply switching our existing flash messages to behave more like the "default" probably isn't feasible, because so much of TC has assumptions about how our custom flash messages work. But, at some point we need to be able to take stock of what we've got, whether we are happy with it or not, and decide what we want the future to look like.

This also touches on the point I was trying to make here:
https://github.com/conversation/tc-assets/pull/1#discussion_r191285494

Is it really valuable to be persisting with things we've never really been happy with when we could be evaluating existing libraries that we can either fork or stick a theme over and call it a day?

To be clear, I think that documenting our re-usable components is extremely valuable, because having to design components in isolation encourages better design. 

I just don't know if that value applies to re-implementing things like buttons and flash messages for the thousandth time, simply because other offerings were Not Invented Here™

As an example, are we planning to fiddle endlessly with the layout of buttons until they look good on every browser? Because currently in Firefox the text is not aligned:

screenshot at 2018-06-04 13-06-50

...or is it better to leverage existing work and spend our effort on creating things that don't already exist?

**Comment by mark-cipolla** [comment]
> custom headings are non-standard and unnecessary

There's no custom heading, FYI.

**Comment by nickbrowne** [comment]
Whatever the implementation is, we seem to have three variants already, "heading with underline", "slightly larger heading with no underline" (and different padding/margin), and "no heading".

**Comment by markcipolla** [comment]
> Whatever the implementation is, we seem to have three variants already, "heading with underline", "slightly larger heading with no underline" (and different padding/margin), and "no heading".

**Comment by mark-cipolla** [comment]
> My main concern is that it seems less reusable to have a shared component which has to be used in a certain way. Do all our apps display alerts in exactly the same way? I get that we are not trying to rebuild bootstrap here, but maybe we should aim to keep things generic and reusable?

Shall we close this PR then? If this component isn't a good candidate, let's kill with 🔥 

> Firstly, I don't like the inconsistency with the way we render all our storybook components (under the Display heading). 

The `<Flash>` component is now under the display sidebar tab.

**Comment by mark-cipolla** [comment]
> Is it really valuable to be persisting with things we've never really been happy with when we could be evaluating existing libraries that we can either fork or stick a theme over and call it a day?
> I just don't know if that value applies to re-implementing things like buttons and flash messages for the thousandth time, simply because other offerings were Not Invented Here™
> As an example, are we planning to fiddle endlessly with the layout of buttons until they look good on every browser? Because currently in Firefox the text is not aligned:

It's a good, important question.

Do we _want_ to do this?
I _guess_ we can use something like bootstrap, some library, but we'd be dropping a lot of the TC "feel". 

I know @nickbrowne raised it in a retro, but we didn't really delve to deep into discussing it. What say everyone?

**Comment by nullobject** [comment]
> What say everyone?

I'm pretty interested to see how much could leverage a 3rd party library like Bootstrap. It would be nice to not have to re-invent (and maintain) another button, alert, etc. I don't think we want _all_ of bootstrap, but the common components seem nice.

I'd be surprised if we couldn't customise things (at least the colours, etc.) to give the components a TC feel. I was looking at [reactstrap](https://reactstrap.github.io/components/alerts/) but there are others out there.

**Comment by benmacleod** [comment]
It seems we're trying to satisfy different imperatives here:

- provide a how to guide of components and other things (colour selections, etc.) to choose from when building new bits of UI which will save time and effort by helping you find the right component / colour, etc., knowing that what you choose is TC-approved, and will make your new bit of UI look and feel "like TC"
- have the components we use be battle-hardened (reasonable test coverage, support, a community of other users, cross-browser compatibility, etc.)

I share people's skepticism about making/maintaining one's own buttons, etc. I suspect that 3rd party libraries like Bootstrap or ZenDesk Garden, suitably branded by some customization, could provide an answer. Introducing a new component set holus bolus could be too big a project for just now, but introducing parts piecemeal may be feasible. If we just put the components we actually use in this library, I think it could maybe keep the guide function alive without having to compromise too much.

I'd love to see this library grow slowly, and only then when we are prepared to actually push out the given component through all or some significant part of our app eco-system. I think that that would guarantee that every component in there would definitely be the right one to reach for - because it will be the one we _have_ reached for. It'd encourage us to use more battle-hardened components, and reduce speculative generalization. If that means that the only thing in there for now is the colour guide and a re-styled Bootstrap button, say, I wouldn't complain. It feels more important to be authoritative than comprehensive at this stage of things.

**Comment by jameshill** [comment]
I think @benmacleod response hit the nail on the head.

In particular:

> Introducing a new component set holus bolus could be too big a project for just now.

Also, while the flash notice isn't what we want right now (i loath it), it is what's being used in analytics, and by documenting it first, we create a place in which we can have the discussion around replacing it for something else.

I totally agree we should be leveraging existing libraries, but it'd be nice to have a plan in place before committing.

Also, I should be clear, I'm not in favour of taking non-react/backbone components and reactifying them only to be essentially documented in storybook, i believe the storybook project is just to get it up and running in TC, so that if a react-component is made, it's documented immediately.

**Comment by mark-cipolla** [comment]
Okay, so I'll close this PR, as we all seem to agree the current flash display is pretty poor.

None of the components I've added to storybook so far have made _for_ storybook, or were non-react components _made into_ react components; they've been lifted off TC or Analytics.

> I'd love to see this library grow slowly, and only then when we are prepared to actually push out the given component through all or some significant part of our app eco-system. I think that that would guarantee that every component in there would definitely be the right one to reach for - because it will be the one we have reached for. It'd encourage us to use more battle-hardened components, and reduce speculative generalization. If that means that the only thing in there for now is the colour guide and a re-styled Bootstrap button, say, I wouldn't complain. It feels more important to be authoritative than comprehensive at this stage of things.

@benmacleod's phrasing pretty much sums up my opinions. 👏

**Comment by nullobject** [comment]
I agree. I think we should start using all the components we've already added to this library. I'm sure it's all going to work sweet, but it would be nice to double-check this before we add any more.

I'm curious about the update process for our apps. Is it just a matter of changing the tc-assets tag in `packages.json` and everything will just work?

**Comment by mark-cipolla** [comment]
> would be nice to double-check this

Double check what? 

> I'm curious about the update process for our apps. Is it just a matter of changing the tc-assets tag in packages.json and everything will just work?

Pretty much, yes.

**Comment by nullobject** [comment]
> Double check what?

For example, ensure that if we swap out the `ToggleSwitch` in TC for the tc-assets `ToggleSwitch` component that it still works exactly the same.

If we have a bunch of unused components in tc-assets then we risk some of them not working as we might expect.

**Comment by mark-cipolla** [comment]
> For example, ensure that if we swap out the ToggleSwitch in TC for the tc-assets ToggleSwitch component that it still works exactly the same.
> 
> If we have a bunch of unused components in tc-assets then we risk some of them not working as we might expect.

Oh, absolutely 100% ;)

**Comment by jameshill** [comment]
> None of the components I've added to storybook so far have made for storybook, or were non-react components made into react components; they've been lifted off TC or Analytics.

**Pull request closed without merging**
